# ===================================================================
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
eureka:
  instance:
    appname: config
    instance-id: config:${spring.application.instance-id:${random.value}}
    prefer-ip-address: true
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
    hostname: localhost

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['refresh', 'health', 'info']
  info:
    git:
      mode: full
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
  application:
    name: config
  messages:
    basename: i18n/messages

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
